apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Application
    name: minio
  patch: |-
    - op: replace
      path: /spec/source/path
      value: prod/argocd-apps/minio
